name: Build and Push Docker Images on PR Merge

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (or GitHub Packages)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Step 3: Build and push backend image
      - name: Build and push Backend image
        id: build_push_backend
        uses: docker/build-push-action@v3
        with:
          context: ./server  
          file: Dockerfile
          push: true  
          tags: hegedus-mark/rizzy-app/api:latest  

      # Step 4: Build and push Docker frontend image
      - name: Build and push Docker image 2
        id: build_push_frontend
        uses: docker/build-push-action@v3
        with:
          context: ./client 
          file: Dockerfile  
          push: true  
          tags:  hegedus-mark/rizzy-app/frontend:latest
          build-args: |
            VITE_API_BASE_URL=https://rizzy-app-api-v1.onrender.com

      # Tag images with a unique tag based on the commit hash
      - name: Tag images with commit hash
        run: |
          IMAGE1_TAG=hegedus-mark/rizzy-app/api:${{ github.sha }}
          IMAGE2_TAG=hegedus-mark/rizzy-app/frontend:${{ github.sha }}
          docker tag hegedus-mark/rizzy-app/api:latest $IMAGE1_TAG
          docker tag hegedus-mark/rizzy-app/frontend:latest $IMAGE2_TAG
          docker push $IMAGE1_TAG
          docker push $IMAGE2_TAG
